import { SignIn, SignOutButton, useUser } from "@clerk/nextjs";
import {
  Card,
  Button,
  Display,
  Text,
  Page,
  Input,
  Badge,
  Fieldset,
} from "@geist-ui/core";
import { type List } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
// import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();
  const ctx = api.useContext();
  const [input, setInput] = useState("");
  const { data } = api.lists.getAll.useQuery({ userId: user.user?.id ?? "" });
  const { mutate: createList, isLoading: addLoading } =
    api.lists.create.useMutation({
      onSuccess: () => {
        console.log("success created");
        void ctx.lists.getAll.invalidate();
      },
    });
  const { mutate: deleteList, isLoading: deleteLoading } =
    api.lists.delete.useMutation({
      onSuccess: () => {
        void ctx.lists.getAll.invalidate();
      },
    });

  const handleAdd = () => {
    createList({
      name: input,
      userId: user.user?.id ?? "",
      status: "added",
    });
  };
  const handleDelete = (id: string) => {
    deleteList({
      id,
    });
  };
  return (
    <>
      <Head>
        <title>Keep Up</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!user.isSignedIn && (
          <div className="flex h-screen items-center justify-center">
            <Display shadow>
              <Text h1 className="mx-4 bg-transparent">{`Keep Up`}</Text>
              <SignIn />
            </Display>
          </div>
        )}
        {!!user.isSignedIn && user.user.firstName && (
          <Page>
            <Page.Header>
              <div className="mt-4">
                <Card>
                  <div className="flex justify-between">
                    <div className="self-center text-xl">{`Hi there, ${user.user.firstName}`}</div>
                    <Button type="secondary" auto>
                      <SignOutButton />
                    </Button>
                  </div>
                </Card>
              </div>
            </Page.Header>
            <Page.Content>
              <div className="grid gap-4">
                <div className="flex gap-x-1">
                  <Input
                    label="Note name"
                    clearable
                    onChange={(event) => {
                      setInput(event.target.value);
                    }}
                    onKeyDown={(e) => {
                      if (e.key === "Enter") {
                        e.preventDefault();
                        if (input !== "") {
                          createList({
                            name: input,
                            userId: user.user?.id ?? "",
                            status: "added",
                          });
                          setTimeout(() => setInput(""), 300);
                        }
                      }
                    }}
                    value={input}
                  />
                  <Button
                    auto
                    scale={0.8}
                    onClick={handleAdd}
                    loading={addLoading}
                  >
                    Add
                  </Button>
                </div>
                {data &&
                  data.length > 0 &&
                  data.map((list: List) => (
                    <Fieldset key={list.id}>
                      <Fieldset.Title>{list.name}</Fieldset.Title>
                      <Fieldset.Footer>
                        <Badge type="success">
                          {`${list.createdAt.toLocaleDateString()} ${list.createdAt.toLocaleTimeString()}`}
                        </Badge>
                        <Button
                          type="error"
                          auto
                          scale={1 / 3}
                          font="12px"
                          onClick={() => {
                            handleDelete(list.id);
                          }}
                          loading={deleteLoading}
                        >
                          Delete
                        </Button>
                      </Fieldset.Footer>
                    </Fieldset>
                  ))}
              </div>
            </Page.Content>
          </Page>
        )}
      </main>
    </>
  );
};

export default Home;
